# Generated by Django 2.2 on 2019-04-13 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatusOfPet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('pet_num', models.IntegerField(default=0)),
                ('pet_name', models.CharField(max_length=30)),
                ('eating_style', models.CharField(max_length=30)),
                ('spending_time', models.CharField(max_length=30)),
                ('pet_sex', models.CharField(max_length=10)),
                ('pet_age', models.IntegerField(default=0)),
                ('pet_weight', models.IntegerField(default=0)),
                ('pet_food_type', models.CharField(max_length=40)),
                ('pet_food_brand', models.CharField(max_length=30)),
                ('feeding_amount', models.CharField(max_length=30)),
                ('body_type', models.CharField(max_length=30)),
                ('activity_level', models.CharField(max_length=20)),
                ('pet_issues', models.CharField(max_length=50)),
            ],
        ),
    ]
