# Generated by Django 2.2 on 2019-04-15 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0002_auto_20190414_0122'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=30)),
                ('eating_style', models.CharField(max_length=30)),
                ('pet_sex', models.CharField(max_length=10)),
                ('pet_age', models.IntegerField(default=0)),
                ('pet_weight', models.IntegerField(default=0)),
                ('pet_breed', models.CharField(max_length=30)),
                ('pet_spayed', models.BooleanField(default=False)),
                ('pet_food_type', models.CharField(max_length=40)),
                ('pet_food_brand', models.CharField(max_length=30)),
                ('feeding_amount', models.CharField(max_length=30)),
                ('body_type', models.CharField(max_length=30)),
                ('activity_level', models.CharField(max_length=20)),
                ('pet_issues', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='myprofile',
            old_name='zipcode',
            new_name='zip',
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.DeleteModel(
            name='StatusOfPet',
        ),
        migrations.AddField(
            model_name='petprofile',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnosis.MyProfile'),
        ),
    ]
