# Generated by Django 2.2 on 2019-04-17 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0003_auto_20190415_1712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petprofile',
            old_name='pet_age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='petprofile',
            old_name='pet_sex',
            new_name='age_unit',
        ),
        migrations.RenameField(
            model_name='petprofile',
            old_name='feeding_amount',
            new_name='breed',
        ),
        migrations.RenameField(
            model_name='petprofile',
            old_name='pet_breed',
            new_name='food_brand',
        ),
        migrations.RenameField(
            model_name='petprofile',
            old_name='pet_food_type',
            new_name='food_type',
        ),
        migrations.RenameField(
            model_name='petprofile',
            old_name='pet_weight',
            new_name='ideal_weight',
        ),
        migrations.RenameField(
            model_name='petprofile',
            old_name='pet_spayed',
            new_name='issue_check',
        ),
        migrations.RenameField(
            model_name='petprofile',
            old_name='pet_issues',
            new_name='issues',
        ),
        migrations.RenameField(
            model_name='petprofile',
            old_name='pet_food_brand',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='petprofile',
            old_name='pet_name',
            new_name='treats_amount',
        ),
        migrations.AddField(
            model_name='petprofile',
            name='sex',
            field=models.CharField(default='he', max_length=10),
        ),
        migrations.AddField(
            model_name='petprofile',
            name='spayed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='petprofile',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
