# Generated by Django 2.2 on 2019-04-17 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0004_auto_20190417_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petprofile',
            name='issue_check',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='petprofile',
            name='spayed',
            field=models.CharField(max_length=10),
        ),
    ]
