# Generated by Django 2.2 on 2019-04-21 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0005_auto_20190417_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='address',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='name',
            field=models.CharField(default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='spending_time',
            field=models.CharField(default='0', max_length=30),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='zip',
            field=models.CharField(default='-', max_length=10),
        ),
        migrations.AlterField(
            model_name='petprofile',
            name='activity_level',
            field=models.CharField(default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='petprofile',
            name='age_unit',
            field=models.CharField(default='years', max_length=10),
        ),
        migrations.AlterField(
            model_name='petprofile',
            name='body_type',
            field=models.CharField(default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='petprofile',
            name='breed',
            field=models.CharField(default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='petprofile',
            name='eating_style',
            field=models.CharField(default='canBePicky', max_length=30),
        ),
        migrations.AlterField(
            model_name='petprofile',
            name='food_brand',
            field=models.CharField(default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='petprofile',
            name='food_type',
            field=models.CharField(default='dry', max_length=40),
        ),
        migrations.AlterField(
            model_name='petprofile',
            name='issue_check',
            field=models.CharField(default='no', max_length=20),
        ),
        migrations.AlterField(
            model_name='petprofile',
            name='issues',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AlterField(
            model_name='petprofile',
            name='name',
            field=models.CharField(default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='petprofile',
            name='spayed',
            field=models.CharField(default='-', max_length=10),
        ),
        migrations.AlterField(
            model_name='petprofile',
            name='treats_amount',
            field=models.CharField(default='some', max_length=30),
        ),
    ]
