# Generated by Django 2.2 on 2019-04-26 00:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0006_auto_20190421_0335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(default='-', max_length=40)),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2019, 4, 26, 0, 18, 35, 371027), max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnosis.MyProfile')),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosisImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(default='-', max_length=30)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnosis.Diagnosis')),
            ],
        ),
    ]
