# Generated by Django 2.2 on 2019-04-26 22:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0008_auto_20190426_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='diagnosis_pic',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 26, 22, 34, 4, 568898, tzinfo=utc), max_length=30),
        ),
        migrations.DeleteModel(
            name='DiagnosisImage',
        ),
    ]
