# Generated by Django 2.2 on 2019-04-26 22:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0009_auto_20190426_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 26, 22, 38, 8, 848253, tzinfo=utc), max_length=30),
        ),
    ]
