# Generated by Django 2.2 on 2019-04-26 22:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0011_auto_20190426_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='diagnosis_pic',
            field=models.ImageField(default='Users/JangChan/PycharmProjects/PetAndPeople/petandpeople/diagnosis/static/pic_folder/None/no-img.jpg', upload_to='Users/JangChan/PycharmProjects/PetAndPeople/petandpeople/diagnosis/static/pic_folder'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 26, 22, 52, 9, 588700, tzinfo=utc), max_length=30),
        ),
    ]
