# Generated by Django 2.2 on 2019-04-26 23:01

import datetime
import django.core.files.storage
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0012_auto_20190426_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='diagnosis_pic',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/static/pic_folder'), upload_to='diagnosis_pic'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 26, 23, 1, 24, 565190, tzinfo=utc), max_length=30),
        ),
    ]
