# Generated by Django 2.2 on 2019-04-27 00:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0017_auto_20190427_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='diagnosis_pic',
            field=models.ImageField(blank=True, null=True, upload_to='diagnosis_pic/'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 27, 0, 40, 24, 749803, tzinfo=utc), max_length=30),
        ),
    ]
