# Generated by Django 2.2 on 2019-04-27 02:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0020_auto_20190427_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 27, 2, 49, 7, 693241, tzinfo=utc), max_length=30),
        ),
    ]
