# Generated by Django 2.2 on 2019-04-28 07:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0022_auto_20190428_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='diagnosis_pic',
            field=models.ImageField(blank=True, null=True, upload_to='diagnosis_image'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 28, 7, 18, 51, 151274, tzinfo=utc), max_length=30),
        ),
    ]
