# Generated by Django 2.2 on 2019-04-29 00:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0023_auto_20190428_0718'),
    ]

    operations = [
        migrations.AddField(
            model_name='petprofile',
            name='hair',
            field=models.CharField(default='-', max_length=10),
        ),
        migrations.AddField(
            model_name='petprofile',
            name='size',
            field=models.CharField(default='-', max_length=10),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='diagnosis_pic',
            field=models.FileField(blank=True, null=True, upload_to='diagnosis_image'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 29, 0, 36, 12, 411501, tzinfo=utc), max_length=30),
        ),
    ]
