# Generated by Django 2.2 on 2019-04-29 01:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0024_auto_20190429_0036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petprofile',
            name='issue_check',
        ),
        migrations.AddField(
            model_name='petprofile',
            name='allergies',
            field=models.CharField(default='no', max_length=10),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 29, 1, 45, 25, 784286, tzinfo=utc), max_length=30),
        ),
        migrations.AlterField(
            model_name='petprofile',
            name='issues',
            field=models.CharField(default='no', max_length=50),
        ),
    ]
