# Generated by Django 2.2 on 2019-04-29 02:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0025_auto_20190429_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 29, 2, 2, 4, 804784, tzinfo=utc), max_length=30),
        ),
    ]
