# Generated by Django 2.2 on 2019-04-30 20:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0026_auto_20190429_0202'),
    ]

    operations = [
        migrations.CreateModel(
            name='DSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(default='-', max_length=10)),
                ('age_unit', models.CharField(default='-', max_length=10)),
                ('weight', models.CharField(default='-', max_length=40)),
                ('body_type', models.CharField(default='-', max_length=40)),
                ('ideal_weight', models.CharField(default='-', max_length=40)),
                ('activity_level', models.CharField(default='-', max_length=40)),
                ('food_type', models.CharField(default='-', max_length=40)),
                ('hair', models.CharField(default='-', max_length=40)),
                ('size', models.CharField(default='-', max_length=40)),
                ('allergies', models.CharField(default='no', max_length=10)),
                ('issues', models.CharField(default='no', max_length=10)),
                ('result', models.CharField(default='-', max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 30, 20, 16, 33, 112084, tzinfo=utc), max_length=30),
        ),
    ]
