# Generated by Django 2.2 on 2019-04-30 21:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0027_auto_20190430_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 30, 21, 34, 58, 196398, tzinfo=utc), max_length=30),
        ),
    ]
