# Generated by Django 2.2 on 2019-05-01 09:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0028_auto_20190430_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 1, 9, 5, 6, 837269, tzinfo=utc), max_length=30),
        ),
    ]
